stages:
  - cache
  - build
  - deploy

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository/
    - target/

build_non_prod:
  tags:
    - non-prod-001
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS clean install -DskipTests


deploy_non_prod:
  stage: deploy
  tags:
    - non-prod-001
  script:
    - mvn -Pdeploy-non-prod initialize beanstalk:upload-source-bundle beanstalk:create-application-version beanstalk:blue-green beanstalk:replace-environment beanstalk:tag-environment
  environment:
      name: non-prod

build_prod:
  tags:
    - prod-001
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS clean install
  when: manual

deploy_prod:
  stage: deploy
  tags:
    - prod-001
  script:
    - mvn -Pdeploy-prod initialize beanstalk:upload-source-bundle beanstalk:create-application-version beanstalk:replace-environment
  environment:
      name: non-prod
  when: manual