version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    network_mode: host
    container_name: zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka:1.1.0
    network_mode: host
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.99.101
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: 192.168.99.101:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
