version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    network_mode: host
    container_name: zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka:1.0.1
    network_mode: host
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.99.102
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: 192.168.99.102:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  sca-events:
      image: org/sca-events
      network_mode: host
      container_name: sca-events
      depends_on:
        - kafka
        - zookeeper
      ports:
        - "5000:5000"
      environment:
        SPRING_KAFKA_PRODUCER_BOOTSTRAP-SERVERS: 192.168.99.102:9092
        SPRING_KAFKA_CONSUMER_BOOTSTRAP-SERVERS: 192.168.99.102:9092
        ORG_SCA_EVENTS_HOME: /tmp
      volumes:
        - /tmp/docker/sca-events:/tmp
